# Generated by Django 5.1.3 on 2025-06-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_ai_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ai_image',
        ),
    ]
