# Generated by Django 5.1.3 on 2025-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_ai_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ai_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
