# Generated by Django 4.2.11 on 2024-11-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_total_copies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookcopy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='copy_number',
        ),
    ]
