# Generated by Django 4.2.11 on 2024-11-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_bookcopy_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrental',
            name='fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bookrental',
            name='status',
            field=models.CharField(choices=[('rented', 'Wypożyczona'), ('returned', 'Zwrócona'), ('overdue', 'Po terminie')], default='rented', max_length=10),
        ),
    ]
