# Generated by Django 4.2.11 on 2024-11-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrental',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
    ]
