# Generated by Django 4.2.11 on 2024-11-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_opinion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='useruser',
            new_name='user',
        ),
    ]
